### PR TITLE
65 feat contributors profile page

### LINKED ISSUE #65: Feat: Contributors profile page
### Features
- Create profile of each contributors,
- Display their name and occupation as contributed in the `.mdx` file
- Show their `Github` profile avatar and bio
- Add Introduction, Skills, Socials section as of now
- Build a `Tab` mdx component 

### Screenshots

_No response_

### Additional Information

If you want to contribute to this, instead of creating pull request direct on `main` branch create on here

### PR DESCRIPTION
**Pull request by sboy99**
This PR will add a new contributor page layout along with some style components. Also add some custom rehype plugins. Provides a better looks for profile page

Closes #65 

## Changes proposed
- Added new structured and styled contributor profile page
- Added rehype plugin
- Added mdx components

### CODE REVIEW

**Comment by Aadarsh805** [comment]
@sboy99 why protected deployment

**Comment by sboy99** [comment]
I randomly opened it, I am turning it off right now

**Review by Aadarsh805 — DISMISSED** [review]
Everything seems cool, can we merge it so that I can add those prev and next button

**Comment by Aadarsh805** [comment]
This pr does not include the projects section??

**Comment by Aadarsh805** [comment]
> This pr does not include the projects section??

You can finish that too, then merge

**Comment by sboy99** [comment]
Yes, Actually its separate from documentation page, you can start work on prev & next  as they are isolated and has nothing to do with contributor profile page

**Comment by Aadarsh805** [comment]
> Yes, Actually its separate from documentation page, you can start work on prev & next as they are isolated and has nothing to do with contributor profile page

Yes realized that later

**Review by Aadarsh805 — APPROVED** [review]
Looks great

**Comment by Aadarsh805** [comment]
How to add links to these

image

**Pull request merged**
