### PR TITLE
Added Badges

### LINKED ISSUE #154: DOC: Add badges to the readme
**What's wrong with the documentation?**
There's nothing wrong, but I would like to enhance it by adding badges.

**Submit screenshots**
image

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**
Fixes #154 

image

### CODE REVIEW

**Comment by priyankarpal** [comment]
## suggestions for you
- whenever you create a PR/issue try to add a good title. 

You can check the docs about commits https://gitopener.vercel.app/guides/general-terminology/How-to-write-professional-commits

**Comment by Soumya-Kushwaha** [comment]
> ## suggestions for you
> * whenever you create a PR/issue try to add a good title.
> 
> You can check the docs about commits https://gitopener.vercel.app/guides/general-terminology/How-to-write-professional-commits

I'll take care @priyankarpal

**Comment by sboy99** [comment]
Hey, really sorry for the lateness. I wasn't active because of some reason. Planning to start it again and getting frequent

**Comment by Soumya-Kushwaha** [comment]
Thank you @sboy99

**Pull request merged**
