### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by ripeliz**
## Changes proposed

Fixed grammar in readme.
Fixed broken links in readme.

## Screenshots

image
image

### CODE REVIEW

**Review by Aadarsh805 — DISMISSED** [review]
These are great, thanks for this @ripeliz

**Comment by Aadarsh805** [comment]
@sboy99 can be merged now

**Review by sboy99 — APPROVED** [review]
LGTM 🚀

**Comment by sboy99** [comment]
Great Work @ripeliz . Nice catches. You may work on other open issues.

**Pull request merged**
