### PR TITLE
feat: designed home page

### PR DESCRIPTION
**Pull request by sboy99**
- Added respective components
- Declared types
- Enhanced typography 
- Implemented file content fetching 
- Defined respective markdown files
- Designed home page with tailwindcss

### CODE REVIEW

**Comment by Aadarsh805** [comment]
The design is absolutely perfect, look awesome
one question where's the guide to add your `mdx` file gonna be in the third `start-contributing` section ?

**Comment by sboy99** [comment]
Yeah I think that would be most prominent to add installation guideline in that section.
I will transfer installation guideline there as soon as development of start-contributing get started

**Review by Aadarsh805 — APPROVED** [review]
Looks awesome

**Comment by Aadarsh805** [comment]
You're making it look too good, but I think we should do all the functionalities first

**Comment by Aadarsh805** [comment]
Give me something to do @sboy99

**Comment by sboy99** [comment]
Can you collect the answers mentioned in heading.md?

**Comment by sboy99** [comment]
I just temporarily put installation guideline here after developing start-contributing will move there

**Comment by sboy99** [comment]
Can you suggest me how we can structure the home page so that it does not look like only text? But we need to put the intro here , suggest me a better introduction or you can ask anyone in your connection for the suitable docs, cause I think the major part we left  with is documentation and question answers. After that we focus on building public profile

**Comment by sboy99** [comment]
> You're making it look too good, but I think we should do all the functionalities first

True but typography is a important building block of this project and will be shared in several component so designed some utilities to ease the future task

**Comment by sboy99** [comment]
> Can you suggest me how we can structure the home page so that it does not look like only text? But we need to put the intro here , suggest me a better introduction or you can ask anyone in your connection for the suitable docs, cause I think the major part we left with is documentation and question answers. After that we focus on building public profile

After this doc section we have to reference all the questions with answers.

**Comment by Aadarsh805** [comment]
> 

I'm absolute trash with design thinking

**Comment by Aadarsh805** [comment]
> Can you collect the answers mentioned in heading.md?

I can do this, where to put these answers though, which file

**Comment by Aadarsh805** [comment]
> Can you suggest me how we can structure the home page so that it does not look like only text? But we need to put the intro here , suggest me a better introduction or you can ask anyone in your connection for the suitable docs, cause I think the major part we left with is documentation and question answers. After that we focus on building public profile

image

we can have cards like these for links

**Pull request merged**
