### PR TITLE
Update readme (need some fix though)

### PR DESCRIPTION
**Pull request by Aadarsh805**

### CODE REVIEW

**Comment by Aadarsh805** [comment]
Add other steps to run server

**Review by sboy99 — CHANGES_REQUESTED** [review]
Hey, most of the changes are up to the mark, some needs attention, I already proposed the changes.Please confirm the filename I think it should be `Readme.md` Thank you

**Comment by Aadarsh805** [comment]
> Hey, most of the changes are up to the mark, some need attention, I already proposed the changes.Please confirm the filename I think it should be `Readme.md` Thank you

I was thinking we can keep the contribution guide in contribution.md and then link this file on readme

**Review by sboy99 — APPROVED** [review]
I have changed some of the things  & fixed some broken links, Now its LGTM 🚀

**Comment by Aadarsh805** [comment]
> I have changed some of the things & fixed some broken links, Now its LGTM rocket

Yeah cool looks great now

**Pull request merged**
