### PR TITLE
docs: add how to add svg icons guide

### PR DESCRIPTION
**Pull request by suzy-g38**
## Fixes Issue
I have added the "how-to-add-SVG-icons.mdx" file with the proper guidelines that were mentioned.
Also added images as an example to give the reader proper clarity.

## Screenshots
image
image
image
image
image
image

## Note to reviewers
Hope you will find this useful.
Thank you

### CODE REVIEW

**Comment by priyankarpal** [comment]
I think these images are not needed. You can delete these. 

image

**Comment by suzy-g38** [comment]
> I think these images are not needed. You can delete these.
> 
> image

okay

**Comment by suzy-g38** [comment]
> I think these images are not needed. You can delete these.
> 
> image

I have made the necessary changes.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by suzy-g38** [comment]
> Looks Good 🎉

Hey, I think something is not right in the folder structure. I had to create a pull request so the "starting-contribution" folder renamed as "1. starting-contribution". Can you please check if everything is all right or not?

**Comment by priyankarpal** [comment]
> > Looks Good tada
> 
> Hey, I think something is not right in the folder structure. I had to create a pull request so the "starting-contribution" folder renamed as "1. starting-contribution". Can you please check if everything is all right or not?


I think there is no problem. @sboy99 added this feature in the previous PR. @Sulagna12 you can check it.
- feat: priority-based sorting for docs (#147)

Or if there is a problem then we need to look into it deeply.

**Comment by suzy-g38** [comment]
> > > Looks Good tada
> > 
> > 
> > Hey, I think something is not right in the folder structure. I had to create a pull request so the "starting-contribution" folder renamed as "1. starting-contribution". Can you please check if everything is all right or not?
> 
> I think there is no problem. @sboy99 added this feature in the previous PR. @Sulagna12 you can check it.
> 
> * feat: priority-based sorting for docs ([feat: priority based sorting for docs #147](https://github.com/pbclife/gitopener.vercel.app/pull/147))
> 
> Or if there is a problem then we need to look into it deeply.

okay okay

**Comment by priyankarpal** [comment]
> > > > Looks Good tada
> > > 
> > > 
> > > Hey, I think something is not right in the folder structure. I had to create a pull request so the "starting-contribution" folder renamed as "1. starting-contribution". Can you please check if everything is all right or not?
> > 
> > 
> > I think there is no problem. @sboy99 added this feature in the previous PR. @Sulagna12 you can check it.
> > 
> > * feat: priority-based sorting for docs ([feat: priority based sorting for docs #147](https://github.com/pbclife/gitopener.vercel.app/pull/147))
> > 
> > Or if there is a problem then we need to look into it deeply.
> 
> okay okay

that's the issue: if we remove `1` from the file name it will show at the end.


https://user-images.githubusercontent.com/88102392/231555563-daa773cf-84e9-448d-ae6b-f64a03bab9ab.mp4

**Comment by sboy99** [comment]
@suzy-g38  when you are starting work on a new issue make sure you pull the main branch. Then create a suitable branch 
> git checkout -b `<new branch name>`
Then start working else it can create some issue.
The steps I would recommend you to take now is following
1. Commit all the changes into your current branch (it should not be main branch)
2. Then run `git checkout main`
3. Then run `git pull upstream main`
4. Then checkout to previous branch
5. Now run `git rebase main`

Next put your chances inside `1.start-contributing` dir

**Comment by sboy99** [comment]
So we have introduced the priority bit to sort the files.
Initially what it was sorting files alphabetically, but that was a problem. The files should be in order.
How is this working.
If we put a numeric bit before the file name separated by a period then it would sort based on the priority bit
Otherwise it will sort alphabetically but after the priority bits

**Review by priyankarpal — APPROVED** [review]
Looks Good to me 🎉

**Pull request merged**
